import { MigrationInterface, QueryRunner } from 'typeorm';

export class PopulateCoursesTable1775100000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO courses (course, campus_id) VALUES
        ('Administração', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Agronomia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Agronomia - Campus Curitibanos', (SELECT id FROM campus WHERE name = 'Curitibanos')),
        ('Animação', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Antropologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Arquitetura e Urbanismo', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Arquivologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Artes Cênicas', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Bacharelado em Ciência e Tecnologia', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Biblioteconomia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciência e Tecnologia de Alimentos', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciências Biológicas', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciências Contábeis', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciência da Computação', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciência da Informação', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciência de Dados', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciências Econômicas', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Ciências Sociais', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Cinema', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Design', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Direito', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Educação do Campo', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Educação Física', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Enfermagem', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Química', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Aeroespacial', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia Automotiva', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia Civil', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Civil de Infraestrutura', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia de Alimentos', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia de Aquicultura', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia de Computação', (SELECT id FROM campus WHERE name = 'Araranguá')),
        ('Engenharia de Controle e Automação', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia de Controle e Automação - Campus Blumenau', (SELECT id FROM campus WHERE name = 'Blumenau')),
        ('Engenharia de Energia', (SELECT id FROM campus WHERE name = 'Araranguá')),
        ('Engenharia de Materiais', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia de Materiais - Campus Blumenau', (SELECT id FROM campus WHERE name = 'Blumenau')),
        ('Engenharia de Produção', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia de Transportes e Logística', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia Elétrica', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Eletrônica', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Ferroviária e Metroviária', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia Florestal', (SELECT id FROM campus WHERE name = 'Curitibanos')),
        ('Engenharia Mecânica', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Mecatrônica', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia Naval', (SELECT id FROM campus WHERE name = 'Joinville')),
        ('Engenharia Sanitária e Ambiental', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Engenharia Têxtil', (SELECT id FROM campus WHERE name = 'Blumenau')),
        ('Farmácia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Filosofia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Física', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Fisioterapia', (SELECT id FROM campus WHERE name = 'Araranguá')),
        ('Fonoaudiologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Geografia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Geologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('História', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Jornalismo', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Letras-LIBRAS', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Letras-Línguas Estrangeiras', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Letras-Português', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Licenciatura Intercultural Indígena do Sul da Mata Atlântica', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Matemática', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Matemática Licenciatura', (SELECT id FROM campus WHERE name = 'Blumenau')),
        ('Medicina', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Medicina - Campus Araranguá', (SELECT id FROM campus WHERE name = 'Araranguá')),
        ('Medicina Veterinária', (SELECT id FROM campus WHERE name = 'Curitibanos')),
        ('Meteorologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Museologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Nutrição', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Oceanografia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Odontologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Pedagogia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Psicologia', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Química', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Química – Licenciatura e Bacharelado', (SELECT id FROM campus WHERE name = 'Blumenau')),
        ('Relações Internacionais', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Secretariado Executivo', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Serviço Social', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Sistemas de Informação', (SELECT id FROM campus WHERE name = 'Florianópolis')),
        ('Tecnologias da Informação e Comunicação', (SELECT id FROM campus WHERE name = 'Araranguá')),
        ('Zootecnia', (SELECT id FROM campus WHERE name = 'Florianópolis'))
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM courses`);
  }
}
